<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;
// @codingStandardsIgnoreFile

?>
<?php
/** @var $block \Vnecoms\Membership\Block\Membership*/
?>
<h1 class="pricing-heading"><?php echo __("Pricing overview")?></h1>
<!-- PRICING-TABLE CONTAINER -->
<div class="pricing-table">
    <?php $i = 1;foreach($block->getMembershipCollection() as $_package):?>
    <?php $_package->load($_package->getId())?>
    <div class="membership-block membership-block-<?php echo $i?> membership-block-<?php echo $_package->getId()?>">
        <h2 class="membership-title"><?php echo $_package->getName()?></h2>
        <?php if($_package->getMembershipFeature()):?>
            <div class="membership-featured">
    		  <span class="title-featured"><?php echo __("Featured")?></span>
    		</div>
		<?php endif;?>
        <!-- CONTENT -->
        <div class="membership-content">
            <div class="membership-price">
                <?php /* @escapeNotVerified */ echo $block->getProductPrice($_package) ?>
            </div>
        </div>
        <!-- /CONTENT -->
        <!-- FEATURES -->
        <div class="membership-features">
            <?php echo $_package->getDescription();?>
            <div class="membership-tocart">
                <?php $postParams = $block->getAddToCartPostParams($_package); ?>
                <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                    <select name="membership[duration]"
                        data-validate="{required:true}"
                        id="vnecoms_membership_duration_<?php echo $_package->getId()?>"
                        class="super-attribute-select">
                    </select>
                    <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                    <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                    <?php echo $block->getBlockHtml('formkey')?>
                    <button type="submit"
                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                            class="action tocart primary">
                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                    </button>
                </form>
            </div>
        </div>
        <script type="text/x-magento-init">
        {
            "#vnecoms_membership_duration_<?php echo $_package->getId()?>": {
                "Vnecoms_Membership/js/membership": {
                    "valueFieldSelector": "#vnecoms_membership_duration_<?php echo $_package->getId()?>",
                    "priceHolderSelector": ".membership-block-<?php echo $i;?> .price-box",
                    "durationOptions": <?php /* @escapeNotVerified */ echo $block->getOptionsJSON($_package) ?>,
                    "priceFormat": <?php echo $this->getPriceFormatJSON()?>
                }
            }
        }
        </script>
    </div>
    <?php $i ++;?>
    <?php endforeach;?>
    
    <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
    </script>
</div>
<!-- /PRICING-TABLE -->