<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Adminhtml\Product\Edit\Tab\Price\Tier */
$element = $block->getElement();
?>
<?php $_htmlId      = $block->getElement()->getHtmlId() ?>
<?php $_htmlClass   = $block->getElement()->getClass() ?>
<?php $_htmlName    = $block->getElement()->getName() ?>
<?php $_readonly    = $block->getElement()->getReadonly() ?>

<div class="field" id="attribute-<?php /* @escapeNotVerified */ echo $_htmlId?>-container" data-attribute-code="<?php /* @escapeNotVerified */ echo $_htmlId?>"
     data-apply-to="<?php echo $block->escapeHtml(
         $this->helper('Magento\Framework\Json\Helper\Data')->jsonEncode(
             $element->hasEntityAttribute() ? $element->getEntityAttribute()->getApplyTo() : []
         )
     )?>">
    <label class="label"><span><?php /* @escapeNotVerified */ echo $block->getElement()->getLabel() ?></span></label>
    <div class="control">
        <table class="admin__control-table tiers_table" id="tiers_table">
            <thead>
                <tr>
                    <th class="col-duration required"><?php /* @escapeNotVerified */ echo __('Duration') ?></th>
                    <th class="col-duration-unit required"><?php /* @escapeNotVerified */ echo __('Duration Unit') ?></th>
                    <th class="col-package-price required"><?php /* @escapeNotVerified */ echo __('Price') ?></th>
                    <th class="col-sort-order"><?php /* @escapeNotVerified */ echo __('Sort Order') ?></th>
                    <th class="col-delete"><?php /* @escapeNotVerified */ echo __('Action') ?></th>
                </tr>
            </thead>
            <tbody id="<?php /* @escapeNotVerified */ echo $_htmlId ?>_container"></tbody>
            <tfoot>
                <tr>
                    <td colspan="5" class="col-actions-add"><?php echo $block->getAddButtonHtml() ?></td>
                </tr>
            </tfoot>
        </table>

<script>
require([
    'mage/template',
    "prototype",
    "mage/adminhtml/form"
], function (mageTemplate) {

//<![CDATA[
var tierPriceRowTemplate = '<tr>'
    + '<td class="col-duration">'
        + '<input class="<?php /* @escapeNotVerified */ echo $_htmlClass ?> duration required-entry validate-greater-than-zero" type="text" name="<?php /* @escapeNotVerified */ echo $_htmlName ?>[<%- data.index %>][duration]" value="<%- data.duration %>" id="membership_row_<%- data.index %>_duration" />'
    + '</td>'
    + '<td class="col-duration-unit">'
    + '<select class="<?php /* @escapeNotVerified */ echo $_htmlClass ?> required-entry" name="<?php /* @escapeNotVerified */ echo $_htmlName ?>[<%- data.index %>][duration_unit]" id="membership_row_<%- data.index %>_duration_unit">'
    <?php foreach ($block->getDurationUnits() as $_option): ?>
    + '<option value="<?php /* @escapeNotVerified */ echo $_option['value'] ?>"><?php /* @escapeNotVerified */ echo $block->escapeJsQuote($block->escapeHtml($_option['label'])) ?></option>'
    <?php endforeach ?>
    + '</select></td>'
    + '<td class="col-package-price"><input class="<?php /* @escapeNotVerified */ echo $_htmlClass ?> required-entry validate-greater-than-zero" type="text" name="<?php /* @escapeNotVerified */ echo $_htmlName ?>[<%- data.index %>][price]" value="<%- data.price %>" id="membership_row_<%- data.index %>_price" /></td>'
    + '<td class="col-sort-order"><input class="<?php /* @escapeNotVerified */ echo $_htmlClass ?> validate-digits" type="text" name="<?php /* @escapeNotVerified */ echo $_htmlName ?>[<%- data.index %>][sort_order]" value="<%- data.sort_order %>" id="membership_row_<%- data.index %>_sort_order" /></td>'
    + '<td class="col-delete"><input type="hidden" name="<?php /* @escapeNotVerified */ echo $_htmlName ?>[<%- data.index %>][delete]" class="delete" value="" id="credit_price_row_<%- data.index %>_delete" />'
    + '<button title="<?php /* @escapeNotVerified */ echo $block->escapeHtml(__('Delete Tier')); ?>" type="button" class="action- scalable delete icon-btn delete-product-option" id="membership_row_<%- data.index %>_delete_button" onclick="return durationControl.deleteItem(event);">'
    + '<span><?php /* @escapeNotVerified */ echo __("Delete") ?></span></button></td>'
    + '</tr>';

var durationControl = {
    template: mageTemplate(tierPriceRowTemplate),
    itemsCount: 0,
    addItem : function () {
        <?php if ($_readonly): ?>
        if (arguments.length < 4) {
            return;
        }
        <?php endif; ?>
        var data = {
        	duration: '',
        	duration_unit: '',
        	price: '',
        	sort_order: '',
            readOnly: false,
            index: this.itemsCount++
        };

        if(arguments.length >= 4) {
            data.duration = arguments[0];
            data.duration_unit = arguments[1];
            data.price = arguments[2];
            data.sort_order = arguments[3];
        }
        if (arguments.length == 5) {
            data.readOnly = arguments[4];
        }

        Element.insert($('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container'), {
            bottom : this.template({
                data: data
            })
        });

        $('membership_row_' + data.index + '_duration_unit').value = data.duration_unit;
        
        if (data.readOnly == '1') {
            ['duration', 'duration_unit', 'price', 'sort_order', 'delete'].each(function(idx){
                $('membership_row_'+data.index+'_'+idx).disabled = true;
            });
            $('membership_row_'+data.index+'_delete_button').hide();
        }

        <?php if ($_readonly): ?>
        $('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container').select('input', 'select').each(this.disableElement);
        $('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container').up('table').select('button').each(this.disableElement);
        <?php else: ?>
        $('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container').select('input', 'select').each(function(el){ Event.observe(el, 'change', el.setHasChanges.bind(el)); });
        <?php endif; ?>
    },
    disableElement: function(el) {
        el.disabled = true;
        el.addClassName('disabled');
    },
    deleteItem: function(event) {
        var tr = Event.findElement(event, 'tr');
        if (tr) {
            Element.select(tr, '.delete').each(function(elem){elem.value='1'});
            Element.select(tr, ['input', 'select']).each(function(elem){elem.hide()});
            Element.hide(tr);
            Element.addClassName(tr, 'no-display template');
        }
        return false;
    }
};
<?php foreach ($block->getValues() as $_item): ?>
durationControl.addItem('<?php /* @escapeNotVerified */ echo $_item['duration']*1 ?>', '<?php /* @escapeNotVerified */ echo $_item['duration_unit'] ?>', '<?php /* @escapeNotVerified */ echo $_item['price'] ?>', '<?php /* @escapeNotVerified */ echo $_item['sort_order'] ?>', <?php echo (int)!empty($_item['readonly'])?>);
<?php endforeach; ?>
<?php if ($_readonly): ?>
$('<?php /* @escapeNotVerified */ echo $_htmlId ?>_container').up('table').select('button')
    .each(durationControl.disableElement);
<?php endif; ?>

window.durationControl = durationControl;
//]]>

});
</script>
    </div>
</div>
